config/routes.rb
Rails.application.routes.draw do
  resources :prods
	root 'welcome#index'
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prod.rb
class Prod < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/prods_controller.rb
class ProdsController < ApplicationController
  before_action :set_prod, only: %i[ show edit update destroy ]

  # GET /prods or /prods.json
  def index
    @prods = Prod.all
  end

  # GET /prods/1 or /prods/1.json
  def show
  end

  # GET /prods/new
  def new
    @prod = Prod.new
  end

  # GET /prods/1/edit
  def edit
  end

  # POST /prods or /prods.json
  def create
    @prod = Prod.new(prod_params)

    respond_to do |format|
      if @prod.save
        format.html { redirect_to @prod, notice: "Prod was successfully created." }
        format.json { render :show, status: :created, location: @prod }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prods/1 or /prods/1.json
  def update
    respond_to do |format|
      if @prod.update(prod_params)
        format.html { redirect_to @prod, notice: "Prod was successfully updated." }
        format.json { render :show, status: :ok, location: @prod }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prods/1 or /prods/1.json
  def destroy
    @prod.destroy
    respond_to do |format|
      format.html { redirect_to prods_url, notice: "Prod was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prod
      @prod = Prod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prod_params
      params.require(:prod).permit(:name, :description, :image_url, :delivery)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prods_helper.rb
module ProdsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foundry</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/prods/_form.html.erb
<%= form_with(model: prod, local: true) do |form| %>
  <% if prod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prod.errors.count, "error") %> prohibited this prod from being saved:</h2>

      <ul>
      <% prod.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>
  
   <div class="field">
    <%= form.label :delivery %>
    <%= form.text_field :delivery %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prods/edit.html.erb
<h1>Editing Prod</h1>

<%= render 'form', prod: @prod %>

<%= link_to 'Show', @prod %> |
<%= link_to 'Back', prods_path %>

app/views/prods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Delivery</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prods.each do |prod| %>
      <tr>
        <td><%= prod.name %></td>
        <td><%= prod.description %></td>
        <td><%= prod.image_url %></td>
        <td><%= prod.delivery %></td>
        <td><%= link_to 'Show', prod %></td>
        <td><%= link_to 'Edit', edit_prod_path(prod) %></td>
        <td><%= link_to 'Destroy', prod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prod', new_prod_path %>

app/views/prods/new.html.erb
<h1>New Prod</h1>

<%= render 'form', prod: @prod %>

<%= link_to 'Back', prods_path %>

app/views/prods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prod.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @prod.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @prod.image_url %>
</p>

<p>
  <strong>Delivery:</strong>
  <%= @prod.delivery %>
</p>

<%= link_to 'Edit', edit_prod_path(@prod) %> |
<%= link_to 'Back', prods_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>